src/Entity/TblTeam.php
<?php

namespace App\Entity;

use App\Repository\TblTeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TblTeamRepository::class)]
class TblTeam
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $matches_played = null;

    #[ORM\OneToMany(mappedBy: 'team', targetEntity: TblPlayer::class)]
    private Collection $tblPlayers;

    public function __construct()
    {
        $this->tblPlayers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getMatchesPlayed(): ?int
    {
        return $this->matches_played;
    }

    public function setMatchesPlayed(int $matches_played): static
    {
        $this->matches_played = $matches_played;

        return $this;
    }

    /**
     * @return Collection<int, TblPlayer>
     */
    public function getTblPlayers(): Collection
    {
        return $this->tblPlayers;
    }

    public function addTblPlayer(TblPlayer $tblPlayer): static
    {
        if (!$this->tblPlayers->contains($tblPlayer)) {
            $this->tblPlayers->add($tblPlayer);
            $tblPlayer->setTeam($this);
        }

        return $this;
    }

    public function removeTblPlayer(TblPlayer $tblPlayer): static
    {
        if ($this->tblPlayers->removeElement($tblPlayer)) {
            // set the owning side to null (unless already changed)
            if ($tblPlayer->getTeam() === $this) {
                $tblPlayer->setTeam(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Tests;
use App\Entity\Height;
use App\Entity\Weight;
use App\Entity\Palier;
use App\Entity\Gathering;
use App\Entity\Attendance;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
#[UniqueEntity(fields: ['email'], message: 'Un compte possède déjà cette adresse mail.')]
#[ORM\Table(name:'tbl_user')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $postePrincipal = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $posteSecondaire = null;

    #[ORM\Column(nullable: true)]
    private ?float $posteCoordX = null;

    #[ORM\Column(nullable: true)]
    private ?float $posteCordY = null;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: Attendance::class)]
    private Collection $attendances;

    #[ORM\OneToMany(mappedBy: 'MadeBy', targetEntity: Gathering::class)]
    private Collection $gatherings;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Tests::class)]
    private Collection $tests;

    public function __construct()
    {
        $this->attendances = new ArrayCollection();
        $this->gatherings = new ArrayCollection();
        $this->tests = new ArrayCollection();
        $this->weights = new ArrayCollection();
        $this->heights = new ArrayCollection();
    }



    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_image = null;



    /**
     * @Assert\NotBlank(groups={"registration", "resetPassword"})
     * @Assert\Length(
     *     min=6,
     *     minMessage="Votre mot de passe doit comporter au moins {{ limit }} caractères",
     *     groups={"registration", "resetPassword"}
     * )
     */
    private $plainPassword;

    #[ORM\Column]
    private ?bool $isCodeValidated = false;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Weight::class)]
    private Collection $weights;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Height::class)]
    private Collection $heights;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Equipe $equipe = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $lastConnection = null;


    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Palier $palier = null;


    #[ORM\Column(nullable: true)]
    private ?int $Classement = null;

    #[ORM\Column(length: 10)]
    private ?string $resp_phone = null;

    #[ORM\Column]
    private ?bool $palier_ended = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Nationality $nationality = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCategory()
    {
        $this_year = new \DateTime('first day of January next year');
        $diff = $this_year->diff($this->date_naissance);

        if ($this->Classement !== null) {
            $diff->y += $this->Classement;
        }
        
        return 'U' . $diff->y;
    }

    /**
     * @return Collection<int, Attendance>
     */
    public function getAttendances(): Collection
    {
        return $this->attendances;
    }

    public function addAttendance(Attendance $attendance): static
    {
        if (!$this->attendances->contains($attendance)) {
            $this->attendances->add($attendance);
            $attendance->setUser($this);
        }

        return $this;
    }

    public function removeAttendance(Attendance $attendance): static
    {
        if ($this->attendances->removeElement($attendance)) {
            // set the owning side to null (unless already changed)
            if ($attendance->getUser() === $this) {
                $attendance->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Gathering>
     */
    public function getGatherings(): Collection
    {
        return $this->gatherings;
    }

    public function addGathering(Gathering $gathering): static
    {
        if (!$this->gatherings->contains($gathering)) {
            $this->gatherings->add($gathering);
            $gathering->setMadeBy($this);
        }

        return $this;
    }

    public function removeGathering(Gathering $gathering): static
    {
        if ($this->gatherings->removeElement($gathering)) {
            // set the owning side to null (unless already changed)
            if ($gathering->getMadeBy() === $this) {
                $gathering->setMadeBy(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, Tests>
     */
    public function getTests(): Collection
    {
        return $this->tests;
    }

    public function addTest(Tests $test): static
    {
        if (!$this->tests->contains($test)) {
            $this->tests->add($test);
            $test->setUser($this);
        }
    }
    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): static
    {
        $this->weight = $weight;

        return $this;
    }


    public function removeTest(Tests $test): static
    {
        if ($this->tests->removeElement($test)) {
            // set the owning side to null (unless already changed)
            if ($test->getUser() === $this) {
                $test->setUser(null);
            }
        }
    }
    public function getProfileImage(): ?string
    {
        return $this->profile_image;
    }

    public function setProfileImage(?string $profile_image): static
    {
        $this->profile_image = $profile_image;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password): self
    {
        $this->plainPassword = $password;

        return $this;
    }

    public function isIsCodeValidated(): ?bool
    {
        return $this->isCodeValidated;
    }

    public function setIsCodeValidated(bool $isCodeValidated): static
    {
        $this->isCodeValidated = $isCodeValidated;


        return $this;
    }

    public function getPostePrincipal(): ?string
    {
        return $this->postePrincipal;
    }

    public function setPostePrincipal(?string $postePrincipal): static
    {
        $this->postePrincipal = $postePrincipal;

        return $this;
    }

    public function getPosteSecondaire(): ?string
    {

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce palier ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    	<button class="btn btn-danger mt-2">
		<i class="fa-solid fa-trash-can"></i>
		</button>
</form>

templates/user/_form.html.twig
{# <link rel="icon" href="/img/logo_usa.ico">
<div class="container-fluid pt-3">
    <div class="card mb-4">
        {{ form_start(form) }}
            <div class="card-header">
                {{ form_widget(form._token) }}
                <div class="row align-items-center">
                    <div class="col-8">
                        <h6 class="mb-0">
                            <div class="form-group {% if form.username.vars.errors|length > 0 %}has-error{% endif %}">
                                {{ form_label(form.username, 'Nom d\'utilisateur : ', {'label_attr': {'class': 'form-label'}}) }}
                                {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
                                {{ form_errors(form.username, {'attr': {'class': 'error-message'}}) }}
                            </div>
                            <div class="form-group {% if form.plainPassword.vars.errors|length > 0 %}has-error{% endif %}">
                                {{ form_label(form.plainPassword, 'Mot de passe : ', {'label_attr': {'class': 'form-label'}}) }}
                                {{ form_widget(form.plainPassword, {'attr': {'class': 'form-control'}}) }}
                                {{ form_errors(form.plainPassword, {'attr': {'class': 'error-message'}}) }}
                            </div>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <h6 class="heading-small text-muted mb-4">Informations</h6>
                <div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group {% if form.first_name.vars.errors|length > 0 %}has-error{% endif %}">
                                {{ form_label(form.first_name, 'Prénom : ', {'label_attr': {'class': 'form-label'}}) }}
                                {{ form_widget(form.first_name, {'attr': {'class': 'form-control'}}) }}
                                {{ form_errors(form.first_name, {'attr': {'class': 'error-message'}}) }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group {% if form.last_name.vars.errors|length > 0 %}has-error{% endif %}">
                                {{ form_label(form.last_name, 'Nom : ', {'label_attr': {'class': 'form-label'}}) }}
                                {{ form_widget(form.last_name, {'attr': {'class': 'form-control'}}) }}
                                {{ form_errors(form.last_name, {'attr': {'class': 'error-message'}}) }}
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        {# <div class="col-lg-4">
                            <div class="form-group {% if form.date_naissance.vars.errors|length > 0 %}has-error{% endif %}">
                                {{ form_label(form.date_naissance, 'Date de naissance : ', {'label_attr': {'class': 'form-label'}}) }}
                                {{ form_widget(form.date_naissance, {'attr': {'class': 'date-select', "id": 'datepicker'}}) }}
                                {{ form_errors(form.date_naissance, {'attr': {'class': 'error-message'}}) }}
                            </div>
                        </div> #}
                        {#<div class="col-lg-4">
                            <div
                                class="form-group {% if form.equipe.vars.errors|length > 0 %}has-error{% endif %}">
                                {{ form_label(form.equipe, 'Équipe : ', {'label_attr': {'class': 'form-label'}}) }}
                                {{ form_widget(form.equipe, {'attr': {'class': 'form-control'}}) }}
                                {{ form_errors(form.equipe, {'attr': {'class': 'error-message'}}) }}
                            </div>
                        </div>
                        <div class="drop-container" id="dropContainer">
                            <span class="drop-title">Déposez le fichier ici</span>
                            ou
                            {{ form_widget(form.profile_image, { 'id': form.profile_image.vars.id, 'attr': {'class': 'form-control', 'onchange': 'handleFileSelect(event)'} }) }}
                        </div>
                    </div><br>
                
                    <button type="submit" class="btn btn-info">{{ button_label|default('Créer') }}</button>
                </div>
            </div>
        {{ form_end(form) }}
    </div>
</div> #}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
<script src="/js/redirect.js"></script>
    <div class="container-fluid pt-3">
        <div class="row removable">
            <div class="col-lg-12">
                <div class="card mb-4">
                    <div class="card-body p-3">
                        <div class="mt-3 text-center">
                            <h1 class="h1 mb-2 display-4">Liste des Utilisateurs</h1>
                        </div><br>
                        <div class="row mb-3">
                            <div class="col-md-6 offset-md-3">
                                <input type="text" id="searchInput" class="form-control" placeholder="Rechercher...">
                            </div>
                        </div>
                        {% if nonValidatedUsers|length > 0 %}
                            <div class="mt-3 text-center">
                                <h1 class="h3 mb-2 display-4">Utilisateurs non validés</h1>
                                <a href="#" class="btn btn-danger text-center" id="reset-palier-btn"><i class="fa-solid fa-triangle-exclamation"></i> Supp. les utilisateurs non vér</a>
                                <script>
                                    document.getElementById('reset-palier-btn').addEventListener('click', function(event) {
                                        event.preventDefault();
                                        if (confirm('Êtes-vous sûr de vouloir supprimer les utilisateurs non vérifiés ?')) {
                                            window.location.href = "{{ path('app_user_del_all') }}";
                                        }
                                    });
                                </script>
                            </div><br>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover text-center">
                                    <thead class="table-dark">
                                        <tr>
                                            <th>Nom d'utilisateur</th>
                                            <th>Prénom</th>
                                            <th>Nom</th>
                                            <th>Date de naissance</th>
                                            <th>Image de profile</th>
                                            <th>Palier</th>
                                            <th>Tel. Resp. Légal</th>
                                            <th>Dernière connexion</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for user in nonValidatedUsers %}
                                            <tr class="userRow">
                                                <td class="align-middle">{{ user.username }}</td>
                                                <td class="align-middle">{{ user.firstName }}</td>
                                                <td class="align-middle">{{ user.lastName }}</td>
                                                <td class="align-middle">{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
                                                <td class="align-middle">{% if user.profileImage != '' %}Oui{% else %}Non{% endif %}</td>
                                                <td class="align-middle">{{ user.palier }}</td>
                                                <td class="align-middle">
                                                    {% if user.respphone is not null %}
                                                        {% set phoneNumber = user.respphone|chunk_split(2, ' ', true) %}
                                                        {{ phoneNumber|trim }}
                                                    {% endif %}
                                                </td>
                                                <td class="align-middle">{{ user.lastConnection ? user.lastConnection|date('d-m-Y') : '' }}</td>
                                                <td class="align-middle" style="text-align: center;">
                                                    <div style="display: flex; justify-content: center; align-items: center;">
                                                        <button  style="margin-right: 5px;" class="btn btn-info mt-2" onclick="redirectToPage('/charts/details/{{ user.id }}')">
                                                            <i class="fa-solid fa-chart-line"></i>
                                                        </button>
                                                        <button class="btn btn-warning mt-2" onclick="redirectToPage('/user/{{ user.id }}/edit')">
                                                            <i class="fa-solid fa-pen"></i>
                                                        </button>
                                                        <span style="margin-left: 5px;">{{ include('user/_delete_form.html.twig') }}</span>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td colspan="8">Il n'y a aucun utilisateur !</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% endif %}
                        <div class="mt-3 text-center">
                            <h1 class="h3 mb-2 display-4">Utilisateurs validés</h1>
                        </div><br>
                        <div class="table-responsive">
                            <table class="table table-striped table-hover text-center">
                                <thead class="table-dark">
                                    <tr>
                                        <th>Nom d'utilisateur</th>
                                        <th>Prénom</th>
                                        <th>Nom</th>
                                        <th>Date de naissance</th>
                                        <th>Image de profile</th>
                                        <th>Palier</th>
                                        <th>Tel. Resp. Légal</th>
                                        <th>Dernière connexion</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for user in users %}
                                        {% if user.IsCodeValidated %}
                                        <tr class="userRow">
                                            <td class="align-middle">{{ user.username }}</td>
                                            <td class="align-middle">{{ user.firstName }}</td>
                                            <td class="align-middle">{{ user.lastName }}</td>
                                            <td class="align-middle">{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
                                            <td class="align-middle">{% if user.profileImage != '' %}Oui{% else %}Non{% endif %}</td>
                                            <td class="align-middle">{{ user.palier }}</td>
                                            <td class="align-middle">
                                                {% if user.respphone is not null %}
                                                    {% set phoneNumber = user.respphone|chunk_split(2, ' ', true) %}
                                                    {{ phoneNumber|trim }}
                                                {% endif %}
                                            </td>
                                            <td class="align-middle">{{ user.lastConnection ? user.lastConnection|date('d-m-Y') : '' }}</td>
                                            <td class="align-middle" style="text-align: center;">
                                                <div style="display: flex; justify-content: center; align-items: center;">
                                                    <button  style="margin-right: 5px;" class="btn btn-info mt-2" onclick="redirectToPage('/charts/details/{{ user.id }}')">
                                                        <i class="fa-solid fa-chart-line"></i>
                                                    </button>
                                                    <button class="btn btn-warning mt-2" onclick="redirectToPage('/user/{{ user.id }}/edit')">
                                                        <i class="fa-solid fa-pen"></i>
                                                    </button>
                                                    <span style="margin-left: 5px;">{{ include('user/_delete_form.html.twig') }}</span>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endif %}
                                    {% else %}
                                        <tr>
                                            <td colspan="8">Il n'y a aucun utilisateur !</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script>
    // JavaScript for filtering users by all columns
    document.getElementById("searchInput").addEventListener("keyup", function() {
        var input, filter, table, tr, td, i, j, txtValue, visible;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.querySelector("table");
        tr = table.querySelectorAll(".userRow");
        for (i = 0; i < tr.length; i++) {
            tr[i].style.display = "none";  // Hide the row initially
            td = tr[i].getElementsByTagName("td");
            for (j = 0; j < td.length; j++) {
                if (td[j]) {
                    txtValue = td[j].textContent || td[j].innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";  // Show the row if a match is found
                        break;  // Exit the inner loop
                    }
                }
            }
        }
    });
</script>
{% endblock %}

templates/user/poste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Selection du poste

{% endblock %}

{% block body %}


<link rel="stylesheet" href="/css/poste.css">

<center>
<div class="container-fluid pt-3">
    <div class="row removable">
        <div class="col-lg-12">
            <div class="card mb-4 h-100">
                <div class="card-body p-3">
                    <div class="terrain">
                        <img src="/images/terrain.jpg" alt="terrain">
                        <button id="gardien" class="poste-button">Gardien</button>
                        <button id="defenseurg" class="poste-button">Défenseur Gauche</button>
                        <button id="defenseurd" class="poste-button">Défenseur Droit</button>
                        <button id="milieug" class="poste-button">Milieu Gauche</button>
                        <button id="milieuoff" class="poste-button">Milieu Offensif</button>
                        <button id="milieudef" class="poste-button">Milieu Defensif</button>
                        <button id="milieud" class="poste-button">Milieu Droit</button>
                        <button id="attaquant" class="poste-button">Attaquant</button>
                    </div>
                    <table>
                        <tr>
                            <td align="center"><div class="poste"><p><button id="selec-pri" class="poste-selec-button">POSTE PRINCIPAL</button><br>Poste sélectionné : <span id="poste-pri">{% if user.postePrincipal != null %}{{ user.postePrincipal }}{% else %}Aucun{% endif %}</span></p></div></td>
                            <td align="center"><div class="poste"><p><button id="selec-sec" class="poste-selec-button">POSTE SECONDAIRE</button><br>Poste sélectionné : <span id="poste-sec">{% if user.posteSecondaire != null %}{{ user.posteSecondaire }}{% else %}Aucun{% endif %}</span></p></div></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    


</center>

<script src="/js/poste.js"></script>


{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Matches_played</th>
                <td>{{ user.matchesPlayed }}</td>
            </tr>
            <tr>
                <th>Weight</th>
                <td>{{ user.weight }}</td>
            </tr>
            <tr>
                <th>Profile_image</th>
                <td>{{ user.profileImage }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}